version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: books_store_postgres_v1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: books_store_v1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: